set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" alternatively, pass a path where Vundle should install plugins
"let path = '~/some/path/here'
"call vundle#rc(path)

" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'
" The following are examples of different formats supported.
" Keep Plugin commands between here and filetype plugin indent on.
" scripts on GitHub repos
Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'tpope/vim-rails.git'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" scripts from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
Plugin 'FuzzyFinder'
" scripts not on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'

" NerdTree Plugin
Bundle 'scrooloose/nerdtree'
autocmd VimEnter * if &filetype !=# 'gitcommit' | autocmd vimenter * NERDTree | endif
autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
"NerdTreeTabs
Bundle 'jistr/vim-nerdtree-tabs'
map <Leader>n <plug>NERDTreeTabsToggle<CR>
let g:nerdtree_tabs_open_on_console_startup=1

Bundle 'ironcamel/vimchat'
Plugin 'mattn/emmet-vim'

Plugin 'vim-scripts/AutoComplPop'

filetype plugin indent on     " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Plugin commands are not allowed.
" Put your stuff after this line
set t_Co=256

syntax on
set number
"filetype plugin on

"set background=dark
"highlight Normal ctermbg=black
"highlight PmenuSel ctermbg=green
":highlight Normal ctermfg=gray ctermbg=darkblue
"highlight PmenuSel ctermfg=gray ctermbg=green

set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set showtabline=2

highlight ColorColumn ctermbg=green
call matchadd('ColorColumn', '\%81v', 100)

"exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~"
"set list

nnoremap  ;  :
nnoremap  :  ;

nnoremap    v   <C-V>
nnoremap <C-V>     v
nnoremap    T      gT
nnoremap    gT     T
nnoremap    tt      gt
nnoremap    gt      tt

set splitbelow
set splitright
colorscheme codeschool
highlight PmenuSel ctermbg=darkgreen
