set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" " alternatively, pass a path where Vundle should install plugins
" "call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'
" The following are examples of different formats supported.
" Keep Plugin commands between here and filetype plugin indent on.
" scripts on GitHub repos
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rails.git'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" scripts from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
Plugin 'FuzzyFinder'
" scripts not on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'

" NerdTree Plugin
Bundle 'scrooloose/nerdtree'
autocmd VimEnter * if &filetype !=# 'gitcommit' | autocmd vimenter * NERDTree | endif
autocmd vimenter * if @% !=# 'vmailbuffer' | autocmd vimenter * NERDTree | endif
autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

"NerdTreeTabs
Bundle 'jistr/vim-nerdtree-tabs'
map <Leader>n <plug>NERDTreeTabsToggle<CR>
let g:nerdtree_tabs_open_on_console_startup=1
Bundle 'briancollins/vim-jst'
Bundle 'moll/vim-node'
Bundle 'sukima/xmledit'
Bundle 'mattn/emmet-vim'
Bundle 'vim-scripts/AutoComplPop'
Bundle 'Raimondi/delimitMate'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'Lokaltog/powerline'
set rtp+=/Users/christopher/.vim/bundle/powerline/powerline/bindings/vim

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on
" "
" " Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line

set t_Co=256
syntax on
set number
"filetype plugin on

"set background=dark
"highlight Normal ctermbg=black
"highlight PmenuSel ctermbg=green
":highlight Normal ctermfg=gray ctermbg=darkblue
"highlight PmenuSel ctermfg=gray ctermbg=green

set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set showtabline=2

highlight ColorColumn ctermbg=green
call matchadd('ColorColumn', '\%81v', 100)



nnoremap  ;  :
nnoremap  :  ;

nnoremap    v   <C-V>
nnoremap <C-V>     v
nnoremap    T      gT
nnoremap    gT     T
nnoremap    tt      gt
nnoremap    gt      tt

set splitbelow
set splitright
colorscheme codeschool

"exec 'set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~'
set nolist
highlight PmenuSel ctermbg=darkgreen
set guifont=consolas:h13
let mapleader=","
map <Leader> <Plug>(easymotion-prefix)
